---
version: 2.1

jobs:
  test:
    working_directory: /tmp/project
    docker:
    - image: matthewschuchard/terraform-plugin
    resource_class: small
    steps:
    - checkout
    - run:
        name: install prereqs
        command: apk add --no-cache --update make
    - run:
        name: build
        command: make build
    - run:
        name: lint
        command: make lint
    - run:
        name: acceptance test
        command: make accept

workflows:
  execute_tests:
    jobs:
    - test
