---
name: build and test

on:
  push:
    branches: [master]
    paths:
    - '**.go'
  pull_request:
    branches: [master]
    paths:
    - '**.go'

jobs:
  go-build:
    runs-on: ubuntu-latest
    container: matthewschuchard/terraform-plugin
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: install prereqs
      run: apk add --no-cache --update make
    - name: build
      run: make build
    - name: lint
      run: make lint
    - name: acceptance test
      run: make accept
