---
name: build and test

on:
  push:
    branches: [master]
    paths:
    - '**.go'
  pull_request:
    branches: [master]
    paths:
    - '**.go'

jobs:
  go-build:
    runs-on: ubuntu-22.04
    container: golang:1.20-alpine
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: install prereqs
      run: apk add --no-cache --update build-base
    - name: build
      run: make build
    - name: acceptance test
      run: make accept
